<?php

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getLatestArticles($limit = null, $array = false)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a, c')
            ->leftJoin('a.comments', 'c')
            ->addOrderBy('a.createdAt', 'DESC');

        if (is_null($limit) === false && $limit > 0)
        {
            $qb->setMaxResults($limit);
        }

        if ($array === true)
        {
            return $qb->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);
        }
        else
        {
            return $qb->getQuery()
            ->getResult();
        }  
    }

    public function getTags()
    {
        $tags = $this->createQueryBuilder('t')
            ->select('t.tags')
            ->getQuery()
            ->getResult();

        $tagsArray = array();

        foreach ($tags as $tag)
        {
            $tagsArray[] = explode(",", $tag);
        }

        foreach ($tagsArray as &$tagElement)
        {
            $tagElement = trim($tagElement);
        }

        return $tagsArray;
    }
}
